### ISSUE TITLE
When you click on any of the "generate component" items nothing happens

### ISSUE THREAD

**Issue by ciresnave** [nut-cheese/generator-file-scaffold#1]
This extension seems like a great idea but it doesn't appear to do ANYTHING.  My VS Code info is as follows:

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by nasir-awan** [comment]
I am having same issue, it does not create any files. All options are not wokring like generate basic react component, generate react component with redux, or generate statelesss react component...

any fix or update on it?

**Comment by MrKou47** [comment]
@ciresnave @nasir-awan sorry guys,i create this extension 2 years ago,and it depend on vscode v1.18.0.I will check the problem in this week.

**Comment by MrKou47** [comment]
guys,i find that it works fine, maybe you should reload this ext.
